export const CARDS = [
    {
        id: 1,
        name: "brute force",
        front: require("./card-fronts/warlord-helmet.png"),
        effect: "a basic attack dealing 1 damage",
        damage: 1,
    },
    {
        id: 2,
        name: "health up",
        front: require("./card-fronts/glass-heart.png"),
        effect: "recover 3hp",
        damage: 1,
    },
    {
        id: 3,
        name: "haunting",
        front: require("./card-fronts/haunting.png"),
        effect: "deal 4 damage but you skip next turn",
        damage: 4,
    },
    {
        id: 4,
        name: "vile water",
        front: require("./card-fronts/vile-fluid.png"),
        effect: "you drink the water and lose 2 hp",
        damage: 2,
    },
    {
        id: 5,
        name: "rally the troops",
        front: require("./card-fronts/rally-the-troops.png"),
        effect: "gain another turn",
        damage: 1,
    },
    {
        id: 6,
        name: "root",
        front: require("./card-fronts/beanstalk.png"),
        effect: "roots enemy for 2 turns dealing 1 damage each turn",
        damage: 1,
    },
    {
        id: 7,
        name: "deadly strike",
        front: require("./card-fronts/deadly-strike.png"),
        effect: "enemy takes 3 damage",
        damage: 3,
    },
    {
        id: 8,
        name: "empowered attack",
        front: require("./card-fronts/embrassed-energy.png"),
        effect: "doubles the next attack",
        damage: 1,
    },
    {
        id: 9,
        name: "cold heart",
        front: require("./card-fronts/cold-heart.png"),
        effect: "freeze the enemy for 2 turns",
        damage: 1,
    },
    {
        id: 10,
        name: "death note",
        front: require("./card-fronts/death-note.png"),
        effect: "enemy takes a randomized damage up to 5",
        damage: Math.floor(Math.random() * (5 - 1) + 1),
    },
]